layout_spectrum: 0.7816189
color:
  saturation: 0.5177066
  lightness: 0.5092749
  brandStrength: 0.6543002
  brandColors:
    - '#090806'
    - '#FFFDFF'
    - '#6D3E24'
    - '#FF8EFF'
    - '#917C5F'
  rhythmicContrast: 0.5404721
typography_spectrum: 0.5247825
name: DustinIngham
