layout_spectrum: 0.4632007
typography_spectrum: 0.5247825
color:
  saturation: 0.9203017
  lightness: 0.9204455
  brandStrength: 0.1497853
  rhythmicContrast: 0.5364029
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: DustinIngham
