layout_spectrum: 0.7816189
typography_spectrum: 0.5247825
color:
  saturation: 0.2074199
  lightness: 0.7866779
  brandStrength: 0.6543002
  brandColors:
    - '#090806'
    - '#FFFDFF'
    - '#6D3E24'
    - '#FF8EFF'
    - '#917C5F'
  rhythmicContrast: 0.9064081
name: DustinIngham
